trigger:
  - master
  - DEVOPS-3448_Pipeline # remove

resources:
  repositories:
    - repository: self
      name: $(Build.Repository.Name)
      type: github
      endpoint: GitHubKontentDevOps
      ref: $(Build.SourceBranch)
    - repository: devops-yaml-templates
      name: devops-yaml-templates
      type: git
      ref: test_matejl # master

extends:
  template: Definitions/Build - Repository/mcp-server.yaml@devops-yaml-templates
