import { z } from "zod";
import { referenceObjectSchema } from "./referenceObjectSchema.js";

// Type definitions for recursive structures
type Reference = { id?: string; codename?: string; external_id?: string };

type RichTextComponent = {
  id: string;
  type: Reference;
  elements: VariantElementInComponent[] | null;
};

type VariantElementInComponent =
  | { element: Reference; value: Reference[] | null } // asset, linked items, multiple choice, taxonomy
  | { element: Reference; value: string | null; searchable_value: string | null } // custom
  | { element: Reference; value: string | null; display_timezone: string | null } // datetime
  | { element: Reference; value: number | null } // number
  | {
      element: Reference;
      value: string | null;
      components: RichTextComponent[] | null;
    } // rich text
  | { element: Reference; value: string | null } // text
  | { element: Reference; value: string | null; mode: "autogenerated" | "custom" }; // url slug

// Non-recursive element schemas
const assetInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.array(referenceObjectSchema).nullable(),
});

const customElementInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.string().nullable(),
  searchable_value: z.string().nullable(),
});

const dateTimeInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.string().nullable(),
  display_timezone: z.string().nullable(),
});

const linkedItemsInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.array(referenceObjectSchema).nullable(),
});

const multipleChoiceInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.array(referenceObjectSchema).nullable(),
});

const numberInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.number().nullable(),
});

const taxonomyInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.array(referenceObjectSchema).nullable(),
});

const textInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.string().nullable(),
});

const urlSlugInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  mode: z.enum(["autogenerated", "custom"]),
  value: z.string().nullable(),
});

// Rich text component schema - uses lazy to handle circular reference
const richTextComponentSchema: z.ZodType<RichTextComponent> = z.lazy(() =>
  z.object({
    id: z.string(),
    type: referenceObjectSchema,
    elements: z.array(elementInComponentSchema).nullable(),
  }),
);

// Rich text element schema - references components which can contain any element type
const richTextInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.string().nullable(),
  components: z.array(richTextComponentSchema).nullable(),
});

// Union schema for elements within components
// Uses z.lazy() to handle circular reference with richTextComponentSchema
const elementInComponentSchema: z.ZodType<VariantElementInComponent> = z.lazy(() => languageVariantElementSchema);

// Top-level language variant element schema
export const languageVariantElementSchema = z.union([
  // Most specific schemas first (with unique distinguishing fields)
  urlSlugInVariantElementSchema, // has unique required 'mode' field
  richTextInVariantElementSchema, // has unique 'components' field
  dateTimeInVariantElementSchema, // has unique nullable 'display_timezone' field
  customElementInVariantElementSchema, // has unique 'searchable_value' field
  numberInVariantElementSchema, // has unique value type (number)

  // Medium specificity (array value types)
  assetInVariantElementSchema, // value: array of references
  linkedItemsInVariantElementSchema, // value: array of references
  multipleChoiceInVariantElementSchema, // value: array of references
  taxonomyInVariantElementSchema, // value: array of references

  // Least specific (basic string value, no unique fields)
  textInVariantElementSchema, // value: string, no distinguishing fields
]);
