import { z } from "zod";
import { referenceObjectSchema } from "./referenceObjectSchema.js";

// Forward declaration for recursive schema
type RichTextComponent = {
  id: string;
  type: { id?: string; codename?: string; external_id?: string };
  elements: RichTextElementInComponent[];
};

type RichTextElementInComponent = {
  element: { id?: string; codename?: string; external_id?: string };
  value: string | null;
  components?: RichTextComponent[] | null;
};

// Recursive schema for rich text elements within components
const richTextElementInComponentSchema: z.ZodType<RichTextElementInComponent> =
  z.lazy(() =>
    z.object({
      element: referenceObjectSchema,
      value: z.string().nullable(),
      components: z.array(richTextComponentSchema).nullable().optional(),
    }),
  );

// Recursive schema for rich text components
const richTextComponentSchema: z.ZodType<RichTextComponent> = z.lazy(() =>
  z.object({
    id: z.string(),
    type: referenceObjectSchema,
    elements: z.array(richTextElementInComponentSchema),
  }),
);

const assetInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.array(referenceObjectSchema).nullable(),
});

const customElementInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.string().nullable(),
  searchable_value: z.string().nullable(),
});

const dateTimeInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.string().nullable(),
  display_timezone: z.string().nullable(),
});

const linkedItemsInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.array(referenceObjectSchema).nullable(),
});

const multipleChoiceInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.array(referenceObjectSchema).nullable(),
});

const numberInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.number().nullable(),
});

const richTextInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.string().nullable(),
  components: z.array(richTextComponentSchema).nullable(),
});

const taxonomyInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.array(referenceObjectSchema).nullable(),
});

const textInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  value: z.string().nullable(),
});

const urlSlugInVariantElementSchema = z.object({
  element: referenceObjectSchema,
  mode: z.enum(["autogenerated", "custom"]),
  value: z.string().nullable(),
});

export const languageVariantElementSchema = z.union([
  // Most specific schemas first (with unique distinguishing fields)
  urlSlugInVariantElementSchema, // has unique required 'mode' field
  richTextInVariantElementSchema, // has unique optional 'components' field
  dateTimeInVariantElementSchema, // has unique nullable 'display_timezone' field
  customElementInVariantElementSchema, // has unique optional 'searchable_value' field
  numberInVariantElementSchema, // has unique value type (number)

  // Medium specificity (array value types)
  assetInVariantElementSchema, // value: array of references
  linkedItemsInVariantElementSchema, // value: array of references
  multipleChoiceInVariantElementSchema, // value: array of references
  taxonomyInVariantElementSchema, // value: array of references

  // Least specific (basic string value, no unique fields)
  textInVariantElementSchema, // value: string, no distinguishing fields
]);
